# -*- encoding: utf-8 -*-
$:.push File.expand_path("../lib", __FILE__)

Gem::Specification.new do |s|
  s.name        = "go_cd_feed"
  s.version     = '1.1.2'
  s.authors     = ["Nikhil Mungel", "Ketan Padegaonkar", "Shishir Das", "Bill DePhillips"]
  s.email       = ["hyfather@gmail.com", "KetanPadegaonkar@gmail.com", "shishir.das@gmail.com", "bill.dephillips@gmail.com"]
  s.homepage    = "http://github.com/rearadmiral/go-api-client.git"
  s.summary     = %q{Client to parse Go CI atom feed}
  s.description = %q{(Fork of go_api_client) This gem parses atom feed generated by the Go.CD server and provides an OO representation of the pipelines and stages.}

  s.rubyforge_project = "go_cd_feed"

  s.files         = `git ls-files`.split("\n") - `git ls-files -- vendor/cache`.split("\n")
  s.test_files    = `git ls-files -- {test,spec,features}/*`.split("\n")
  s.executables   = `git ls-files -- bin/*`.split("\n").map{ |f| File.basename(f) }
  s.require_paths = ["lib"]

  # specify any dependencies here; for example:
  s.add_development_dependency "webmock"
  s.add_development_dependency "simplecov"
  s.add_development_dependency 'rake'
  s.add_development_dependency 'test-unit'

  s.add_runtime_dependency "nokogiri"
end
